### ISSUE TITLE
Named re-exports are not sorted

### ISSUE THREAD

**Issue by mpsijm** [jrdrg/eslint-plugin-sort-exports#11]
Example code:
```js
/* eslint sort-exports/sort-exports: ["error"] */
export {Icon} from "./Icon";
export {Button} from "./Button";
```
I would have expected this plugin to force these exports to be sorted, but it doesn't.

**Comment by jrdrg** [comment]
Just addressed this in https://github.com/jrdrg/eslint-plugin-sort-exports/pull/13
